-- MySQL Script generated by MySQL Workbench
-- Fri May  6 16:04:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 323_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 323_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `323_project` DEFAULT CHARACTER SET utf8 ;
USE `323_project` ;

-- -----------------------------------------------------
-- Table `323_project`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `323_project`.`contact` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `323_project`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `323_project`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `323_project`.`user_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `323_project`.`user_contact` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NULL DEFAULT NULL,
  `contactID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `userID_idx` (`userID` ASC) VISIBLE,
  INDEX `contactID_idx` (`contactID` ASC) VISIBLE,
  CONSTRAINT `contactID`
    FOREIGN KEY (`contactID`)
    REFERENCES `323_project`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `323_project`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
